const desktop = document.querySelector('#desktop');
const input = document.querySelector('#terminal-input');
const output = document.querySelector('#terminal-output');
const form = document.querySelector('#terminal-form');
let zIndex = 10;
let commandHistory = JSON.parse(localStorage.getItem('cyberos-history') || '[]');
let historyIndex = commandHistory.length;
let cwd = '/root';
let activeWindow = document.querySelector('.window.active');

const fileSystem = {
  '/': { home: 'dir', root: 'dir', etc: 'dir', usr: 'dir', var: 'dir', tmp: 'dir', 'README.txt': 'file' },
  '/home': { YC: 'dir', guest: 'dir' },
  '/home/YC': { Desktop: 'dir', Documents: 'dir', Downloads: 'dir', projects: 'dir', '.bashrc': 'file' },
  '/home/YC/Documents': { 'notes.txt': 'file', 'ctf-checklist.md': 'file' },
  '/home/YC/projects': { 'cyberos.md': 'file', 'recon-tools.py': 'file', assets: 'dir' },
  '/root': { 'README.txt': 'file', tools: 'dir', '.bash_history': 'file', labs: 'dir' },
  '/root/tools': { 'network-map.sh': 'file', 'hash-notes.txt': 'file' },
  '/root/labs': { 'packet-analysis.md': 'file', 'reverse-engineering': 'dir' },
  '/etc': { hostname: 'file', hosts: 'file', 'os-release': 'file', ssh: 'dir' },
  '/usr': { bin: 'dir', share: 'dir' }, '/var': { log: 'dir' }, '/tmp': {}
};
const fileContents = {
  '/README.txt': 'CyberOS is a client-side desktop environment.\nEverything here is simulated locally in your browser.',
  '/root/README.txt': 'Welcome, root.\nThis is a safe, simulated filesystem.',
  '/etc/hostname': 'cyberos',
  '/etc/os-release': 'NAME="CyberOS"\nID=cyberos\nPRETTY_NAME="CyberOS Browser Edition"',
  '/home/YC/Documents/ctf-checklist.md': '# CTF checklist\n- Enumerate\n- Validate\n- Document\n- Learn',
  '/root/tools/network-map.sh': '#!/bin/sh\necho "Simulation only"'
};
let explorerPath = '/';

function escapeHtml(value) { return String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function currentPrompt() { return `root@cyberos <b>${cwd === '/root' ? '~' : cwd}</b> #`; }
function print(text, type = 'command-output') { const block = document.createElement('pre'); block.className = type; block.innerHTML = text; output.append(block); output.scrollTop = output.scrollHeight; }
function printCommand(command) { print(`<span class="prompt">${currentPrompt()}</span> ${escapeHtml(command)}`, 'line'); }
function toast(message) { const node = document.querySelector('#toast'); node.textContent = message; node.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove('show'), 1800); }
function normalPath(path = '') { if (!path || path === '~') return '/root'; const result = []; (path.startsWith('/') ? path : `${cwd}/${path}`).split('/').forEach(part => { if (!part || part === '.') return; if (part === '..') result.pop(); else result.push(part); }); return `/${result.join('/')}`; }
function refreshPrompt() { document.querySelector('.terminal-input-row label').innerHTML = currentPrompt(); }
function simulateNmap(target) { const host = target || 'scanme.nmap.org'; return `Starting Nmap 7.95 ( https://nmap.org ) at ${new Date().toLocaleTimeString()}\nNmap scan report for ${host} (45.33.32.156)\nHost is up (0.041s latency).\nNot shown: 997 filtered tcp ports (no-response)\nPORT     STATE SERVICE\n22/tcp   open  ssh\n80/tcp   open  http\n443/tcp  open  https\n\nNmap done: 1 IP address (1 host up) scanned in 1.24 seconds`; }
function simulateDig(domain) { const name = domain || 'example.com'; return `; <<>> DiG 9.18.24 <<>> ${name}\n;; global options: +cmd\n;; Got answer:\n;; ->>HEADER<<- opcode: QUERY, status: NOERROR\n\n;; QUESTION SECTION:\n;${name}.\t\t\tIN\tA\n\n;; ANSWER SECTION:\n${name}.\t\t60\tIN\tA\t93.184.216.34\n\n;; Query time: 22 msec\n;; SERVER: Browser DNS emulator`; }
function neofetch() { return `[ ACCESS GRANTED ]\n\nIDENTITY: YC\nROLE: High School Cybersecurity Researcher\nSTATUS: Active\n\nI’m a high school student obsessed with breaking things just to understand how they work.\n\nMy interests lie in ethical hacking, penetration testing, cryptography, digital forensics, reverse engineering, network security, and CTFs. I spend my time hunting vulnerabilities, analysing systems, writing custom tools, and solving problems that were never meant to be solved easily.\n\nI work primarily with Linux, Python, networking, and low-level systems, constantly experimenting with new techniques and challenging myself through real-world security problems.\n\nOBJECTIVE: Learn. Break. Analyse. Exploit. Secure.\n\n> curiosity.exe --run\n> target = everything\n> permission = granted`; }
async function clientFetch(url, ping = false) { let target = url || 'https://example.com'; if (!/^https?:\/\//i.test(target)) target = `https://${target}`; print(`Connecting to ${escapeHtml(target)} ...`); try { const start = performance.now(); const response = await fetch(target, { method: 'GET', mode: 'cors' }); const elapsed = Math.round(performance.now() - start); if (ping) print(`64 bytes from ${new URL(target).hostname}: icmp_seq=1 ttl=57 time=${elapsed}.0 ms\n--- ${new URL(target).hostname} ping statistics ---\n1 packets transmitted, 1 received, 0% packet loss`); else print(`HTTP/1.1 ${response.status} ${response.statusText}\ncontent-type: ${response.headers.get('content-type') || 'not exposed by CORS'}\n\n[Response received client-side. Body preview intentionally omitted.]`); } catch { print('curl: (6) Could not resolve host or CORS policy blocked response\nThis browser-only terminal makes GET requests directly from your device; no CyberOS server request was made.'); } }
async function run(command) {
  const [bin, ...args] = command.trim().split(/\s+/); const arg = args.join(' '); if (!bin) return;
  const help = `CyberOS shell commands:\n  ls [dir]       list files        cd [dir]       change directory\n  pwd            show directory   cat [file]      read a file\n  echo [text]    print text       date            show time\n  whoami         current user     uname [-a]      system info\n  clear          clear terminal   history         command history\n  neofetch       identity profile help            this guide\n\nNetwork learning tools:\n  curl URL       client-side GET request only\n  ping URL       client-side GET reachability check\n  nmap [host]    simulated port scan output\n  dig [domain]   simulated DNS lookup output\n\nNothing here sends POST requests or talks to a backend.`;
  if (command.trim() === 'sudo rm -rf /') print('YOU HAVE BEEN PWNED!'); else if (bin === 'help') print(help); else if (bin === 'clear') output.innerHTML = ''; else if (bin === 'pwd') print(cwd); else if (bin === 'whoami') print('root'); else if (bin === 'date') print(new Date().toString()); else if (bin === 'uname') print(args.includes('-a') ? 'Linux cyberos 6.8.0-cyberos #1 SMP PREEMPT_DYNAMIC browser x86_64 CyberOS' : 'Linux'); else if (bin === 'echo') print(escapeHtml(arg)); else if (bin === 'history') print(commandHistory.map((item, index) => `${String(index + 1).padStart(4)}  ${item}`).join('\n')); else if (bin === 'neofetch') print(neofetch()); else if (bin === 'ls') { const path = normalPath(arg); print(fileSystem[path] ? Object.keys(fileSystem[path]).join('  ') : `ls: cannot access '${escapeHtml(arg)}': No such file or directory`); } else if (bin === 'cd') { const path = normalPath(arg); if (fileSystem[path]) { cwd = path; refreshPrompt(); } else print(`cd: ${escapeHtml(arg)}: No such file or directory`); } else if (bin === 'cat') { const lookup = normalPath(arg); print(fileContents[lookup] ? escapeHtml(fileContents[lookup]) : `cat: ${escapeHtml(arg)}: No such file or directory`); } else if (bin === 'nmap') print(simulateNmap(arg)); else if (bin === 'dig') print(simulateDig(arg)); else if (bin === 'curl') await clientFetch(arg); else if (bin === 'ping') await clientFetch(arg, true); else if (['mkdir', 'touch', 'rm', 'sudo', 'chmod'].includes(bin)) print(`${bin}: operation not permitted in the browser filesystem`); else print(`${escapeHtml(bin)}: command not found`);
}
form.addEventListener('submit', async event => { event.preventDefault(); const command = input.value.trim(); if (!command) return; printCommand(command); commandHistory.push(command); commandHistory = commandHistory.slice(-100); localStorage.setItem('cyberos-history', JSON.stringify(commandHistory)); historyIndex = commandHistory.length; input.value = ''; await run(command); });
input.addEventListener('keydown', event => { if (event.key === 'ArrowUp') { event.preventDefault(); historyIndex = Math.max(0, historyIndex - 1); input.value = commandHistory[historyIndex] || ''; } if (event.key === 'ArrowDown') { event.preventDefault(); historyIndex = Math.min(commandHistory.length, historyIndex + 1); input.value = commandHistory[historyIndex] || ''; } });

function closeMenus() { document.querySelectorAll('.menu-popover').forEach(menu => menu.classList.add('hidden')); }
function focusWindow(win) { document.querySelectorAll('.window').forEach(item => item.classList.remove('active')); win.classList.remove('hidden'); win.classList.add('active'); win.style.zIndex = ++zIndex; activeWindow = win; if (win.id === 'terminal') setTimeout(() => input.focus(), 0); }
function openApp(id) { const win = document.getElementById(id); if (win) focusWindow(win); closeMenus(); }
function windowAction(action) { if (!activeWindow) return; if (action === 'close' || action === 'minimize') activeWindow.classList.add('hidden'); if (action === 'maximize') activeWindow.classList.toggle('maximized'); if (action === 'tile') { const visible = [...document.querySelectorAll('.window:not(.hidden)')]; visible.forEach((win, index) => { win.classList.remove('maximized'); win.style.left = `${20 + (index % 3) * 33}vw`; win.style.top = `${55 + Math.floor(index / 3) * 42}vh`; win.style.width = '31vw'; win.style.height = '37vh'; focusWindow(win); }); } closeMenus(); }
document.querySelectorAll('[data-open]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); openApp(button.dataset.open); }));
document.querySelectorAll('.menu-trigger').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); const menu = document.querySelector(`#${button.dataset.menu}-menu`); const wasOpen = !menu.classList.contains('hidden'); closeMenus(); if (!wasOpen) { const rect = button.getBoundingClientRect(); menu.style.left = `${rect.left}px`; menu.classList.remove('hidden'); } }));
document.querySelectorAll('[data-window-action]').forEach(button => button.addEventListener('click', () => windowAction(button.dataset.windowAction)));
document.querySelectorAll('.window').forEach(win => { win.addEventListener('pointerdown', () => focusWindow(win)); const bar = win.querySelector('.titlebar'); bar.addEventListener('pointerdown', event => { if (event.target.closest('.traffic')) return; focusWindow(win); const rect = win.getBoundingClientRect(), x = event.clientX - rect.left, y = event.clientY - rect.top; const move = moveEvent => { win.style.left = `${Math.max(0, Math.min(moveEvent.clientX - x, innerWidth - 80))}px`; win.style.top = `${Math.max(31, Math.min(moveEvent.clientY - y, innerHeight - 80))}px`; }; const end = () => { document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', end); }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', end); }); win.querySelector('.close').addEventListener('click', () => win.classList.add('hidden')); win.querySelector('.minimize').addEventListener('click', () => { win.classList.add('hidden'); toast(`${win.querySelector('.titlebar span').textContent} minimized`); }); win.querySelector('.maximize').addEventListener('click', () => win.classList.toggle('maximized')); const handle = win.querySelector('.resize-handle'); handle.addEventListener('pointerdown', event => { event.preventDefault(); const rect = win.getBoundingClientRect(), startX = event.clientX, startY = event.clientY; const move = moveEvent => { win.style.width = `${Math.max(320, rect.width + moveEvent.clientX - startX)}px`; win.style.height = `${Math.max(220, rect.height + moveEvent.clientY - startY)}px`; }; const end = () => { document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', end); }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', end); }); });

function renderFiles(path = explorerPath) { explorerPath = path; document.querySelector('#file-path').textContent = path; document.querySelector('#file-preview').classList.add('hidden'); const grid = document.querySelector('#file-grid'); grid.innerHTML = ''; Object.entries(fileSystem[path] || {}).forEach(([name, type]) => { const item = document.createElement('button'); item.className = 'file-entry'; item.innerHTML = `<i class="${type === 'dir' ? 'folder-icon' : 'doc-icon'}">${type === 'dir' ? '▰' : '▤'}</i><span>${escapeHtml(name)}</span>`; item.addEventListener('click', () => { const target = `${path === '/' ? '' : path}/${name}`; if (type === 'dir') renderFiles(target); else { const preview = document.querySelector('#file-preview'); preview.textContent = fileContents[target] || `${name}\n\nNo preview available for this simulated file.`; preview.classList.remove('hidden'); } }); grid.append(item); }); document.querySelectorAll('#file-sidebar button').forEach(button => button.classList.toggle('selected', button.dataset.path === path)); }
function setupFiles() { const sidebar = document.querySelector('#file-sidebar'); [['⌂ Root', '/'], ['⌂ /root', '/root'], ['▰ /home', '/home'], ['▰ YC', '/home/YC'], ['⚙ /etc', '/etc'], ['⇩ /tmp', '/tmp']].forEach(([label, path]) => { const button = document.createElement('button'); button.textContent = label; button.dataset.path = path; button.addEventListener('click', () => renderFiles(path)); sidebar.append(button); }); document.querySelector('#file-up').addEventListener('click', () => renderFiles(explorerPath === '/' ? '/' : explorerPath.split('/').slice(0, -1).join('/') || '/')); renderFiles('/'); }
function setupCalculator() { let expression = ''; const display = document.querySelector('#calc-display'); document.querySelectorAll('[data-calc]').forEach(button => button.addEventListener('click', () => { const key = button.dataset.calc; if (key === 'clear') expression = ''; else if (key === 'delete') expression = expression.slice(0, -1); else if (key === 'operator') expression += '%'; else if (key === 'equals') { try { if (!/^[0-9.+\-*/%() ]+$/.test(expression)) throw new Error(); expression = String(Function(`"use strict"; return (${expression})`)()); } catch { expression = 'Error'; } } else expression = expression === 'Error' ? key : expression + key; display.textContent = expression || '0'; })); }
function setupCalendar() { const now = new Date(); document.querySelector('#calendar-month').textContent = now.toLocaleString(undefined, { month: 'long' }); document.querySelector('#calendar-year').textContent = now.getFullYear(); document.querySelector('#calendar-today').textContent = now.toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' }); const grid = document.querySelector('#calendar-grid'); const first = new Date(now.getFullYear(), now.getMonth(), 1).getDay(); const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); for (let i = 0; i < first; i += 1) grid.append(document.createElement('span')); for (let day = 1; day <= days; day += 1) { const node = document.createElement('button'); node.textContent = day; if (day === now.getDate()) node.classList.add('today'); grid.append(node); } }
function setupMatrix() { const canvas = document.querySelector('#matrix-rain'); const context = canvas.getContext('2d'); const glyphs = '01<>[]{}()#$%&*+=アイウエオカキクケコ'; let columns = []; const resize = () => { canvas.width = innerWidth; canvas.height = innerHeight; columns = Array(Math.ceil(canvas.width / 17)).fill(1); }; const draw = () => { context.fillStyle = 'rgba(2, 10, 8, 0.16)'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#61f59b'; context.font = '14px monospace'; columns.forEach((drop, index) => { context.fillText(glyphs[Math.floor(Math.random() * glyphs.length)], index * 17, drop * 17); if (drop * 17 > canvas.height && Math.random() > 0.975) columns[index] = 0; columns[index] += 1; }); requestAnimationFrame(draw); }; resize(); addEventListener('resize', resize); draw(); }
function updateClock() { document.querySelector('#clock').textContent = new Intl.DateTimeFormat(undefined, { weekday: 'short', hour: 'numeric', minute: '2-digit' }).format(new Date()); }
document.querySelector('#clock').addEventListener('click', () => openApp('calendar')); document.addEventListener('pointerdown', event => { if (!event.target.closest('.menubar')) closeMenus(); }); document.addEventListener('keydown', event => { if (event.metaKey && ['1', '2', '3', '4'].includes(event.key)) { event.preventDefault(); openApp({ 1: 'terminal', 2: 'files', 3: 'calculator', 4: 'calendar' }[event.key]); } });
setupFiles(); setupCalculator(); setupCalendar(); setupMatrix(); updateClock(); setInterval(updateClock, 30000);
